name: SocialCreditsPlugin
version: '${project.version}'
main: me.necroliner.socialcreditsplugin.SocialCreditSystem
api-version: 1.18
authors: [ Necroliner ]
description: displays social credits count
commands:
  scs:
    usage: /<command>
